### ISSUE TITLE
Can make article:not(.not) more readable

### ISSUE THREAD

**Issue by acacheung** [Alo-o/Alo-o.github.io#15]
https://github.com/Alo-o/Alo-o.github.io/blob/master/dobot/index.css#L79

:not(:first-child) or :not(:first-of-type)
then you won't have to create the .not class

**Comment by acacheung** [comment]
what's the question you have here?

**Comment by Alo-o** [comment]
I tried doing this and it wasn't working. It possibly has to do with how my html is set up I guess but I tried a lot of things and it wasn't working for me.
